### ISSUE TITLE
添加用户时接口返回500错误

### ISSUE THREAD

**Issue by fwlst** [TaleLin/lin-cms-flask#115]
**描述 bug**

- 前端管理系统添加用户
- 后端报错500

**你使用哪个版本出现该问题？**

 master 分支
接口地址: /cms/user/register
错误信息：
Traceback (most recent call last):
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/flask_cors/extension.py", line 110, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/flask_cors/extension.py", line 110, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/flask/app.py", line 1719, in handle_user_exception
    return handler(e)
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/lin/core.py", line 206, in handler
    raise e
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/lin/log.py", line 37, in wrap
    response: Response = func(*args, **kwargs)
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/lin/jwt.py", line 30, in wrapper
    return fn(*args, **kwargs)
  File "/Users/fanwei/Desktop/project/python/starter/app/api/cms/user.py", line 32, in register
    form = RegisterForm().validate_for_api()
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/lin/forms.py", line 25, in validate_for_api
    valid = super(Form, self).validate()
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/Users/fanwei/.local/share/virtualenvs/starter-7VRm1H9r/lib/python3.7/site-packages/wtforms/validators.py", line 134, in __call__
    if data is None or (self.min is not None and data < self.min) or \
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by sunlin92** [comment]
前端的版本是0.2.x吗？请尽可能多的提供信息帮助我们复现您的问题，比如添加用户的具体字段，以及浏览器中此请求的报错信息，谢谢！

**Comment by fwlst** [comment]
前端是0.2.x

**Comment by fwlst** [comment]
http://localhost:5000/cms/user/register?handleError=true

**Comment by fwlst** [comment]
http://localhost:5000/cms/user/register?handleError=true

**Comment by fwlst** [comment]
请求截图
![1588222167883](https://user-images.githubusercontent.com/16433398/80673118-0e468a00-8ae1-11ea-946e-928b42afc2e2.jpg)

**Comment by sunlin92** [comment]
看图中的信息好像没有给用户指定一个用户组

**Comment by fwlst** [comment]
那也应该提示选择用户组，不应该报错。

**Comment by sunlin92** [comment]
好的，感谢反馈~
