### ISSUE TITLE
新手，仓库下载代码，目录下面执行pip install -r requirements.txt;全部成功，启动不起来

### ISSUE THREAD

**Issue by bingwq** [TaleLin/lin-cms-flask#132]
![图片](https://user-images.githubusercontent.com/56676131/103867742-d4636400-5102-11eb-8cbe-a502f79004ee.png)

Traceback (most recent call last):
  File "F:\公司\word\python\web2\starter.py", line 6, in <module>
    from app.app import create_app
  File "F:\公司\word\python\web2\app\app.py", line 11, in <module>
    from lin import Lin
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\lin\__init__.py", line 10, in <module>
    from .core import Lin, route_meta, manager
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\lin\core.py", line 19, in <module>
    from .db import db
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\lin\db.py", line 7, in <module>
    from flask_sqlalchemy import SQLAlchemy as _SQLAlchemy, BaseQuery
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 22, in <module>
    import sqlalchemy
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\__init__.py", line 9, in <module>
    from .sql import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\__init__.py", line 8, in <module>
    from .expression import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\expression.py", line 34, in <module>
    from .visitors import Visitable
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\sql\visitors.py", line 28, in <module>
    from .. import util
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\__init__.py", line 8, in <module>
    from .compat import callable, cmp, reduce,  \
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\compat.py", line 234, in <module>
    time_func = time.clock

**Comment by sunlin92** [comment]
请尝试这里的解决办法 #102
