### ISSUE TITLE
0.3x版本 使用flask db init初始化mysql过程报错

### ISSUE THREAD

**Issue by icolor** [TaleLin/lin-cms-flask#133]
windows 7 系统
python3.8
pymysql==1.0.2

过程：
flask db init

错误提示：
(Flask_ENV) C:\Users\Administrator\Desktop\lin-cms-flask-0.3.x>flask db init
XXX lineno: 858, opcode: 0
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\Flask_ENV\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\flask\cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\flask\cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\lin-cms-flask-0.3.x\app\cli\__init__.py", line 21, in db_init
    _db_init(force)
  File "C:\Users\Administrator\Desktop\lin-cms-flask-0.3.x\app\cli\db\init.py", line 32, in init
    db.session.flush()
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\sqlalchemy\orm\session.py", line 2536, in flush
    self._flush(objects)
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\sqlalchemy\orm\session.py", line 2678, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\sqlalchemy\orm\session.py", line 2638, in _flush
    flush_context.execute()
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\sqlalchemy\orm\persistence.py", line 230, in save_obj
    _emit_update_statements(
  File "c:\users\administrator\desktop\flask_env\lib\site-packages\sqlalchemy\orm\persistence.py", line 858, in _emit_update_statements
    needs_version_id = (
SystemError: unknown opcode

**Comment by fuh** [comment]
SystemError: unknown opcode 一般是 python 版本的问题，看你用的好像是 32 位的，换 64 位试试？
