### ISSUE TITLE
windows 执行flask db init 出错

### ISSUE THREAD

**Issue by pengbaba19** [TaleLin/lin-cms-flask#165]
Traceback (most recent call last):
  File "c:\xxxx\appdata\local\programs\python\python37\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "D:\xxx\ljyf\starter\starter.py", line 9, in <module>
    from app.model.lin import (
  File "D:\xxx\ljyf\starter\app\model\lin\__init__.py", line 1, in <module>
    from .group import Group
  File "D:\xxx\ljyf\starter\app\model\lin\group.py", line 1, in <module>
    from lin.model import Group as LinGroup
  File "c:\xxx\appdata\local\programs\python\python37\lib\site-packages\lin\__init__.py", line 18, in <module>
    from .encoder import JSONEncoder, auto_response
  File "c:\xxx\appdata\local\programs\python\python37\lib\site-packages\lin\encoder.py", line 10, in <module>
    from .apidoc import BaseModel
  File "c:\xxxxappdata\local\programs\python\python37\lib\site-packages\lin\apidoc.py", line 7, in <module>
    from pydantic.main import Any, object_setattr, validate_model
ImportError: cannot import name 'object_setattr' from 'pydantic.main' (c:\xxx\appdata\local\programs\python\python37\lib\site-packages\pydantic\main.py)

**Comment by sunlin92** [comment]
你好，无法复现此问题，建议在ide中使用新的初始python环境安装依赖
