### ISSUE TITLE
在前端添加分组的时候。flask后端报错问题

### ISSUE THREAD

**Issue by zyxyuanxiao** [TaleLin/lin-cms-flask#60]
![image](https://user-images.githubusercontent.com/8100661/59404585-a8beb180-8dd9-11e9-805f-c8b2f0992542.png)

最新版本：

再前端操作这个提交添加的时候，相关的：

![image](https://user-images.githubusercontent.com/8100661/59404600-b96f2780-8dd9-11e9-9fa1-e43a118e42aa.png)

这个地方会报错：

报错的异常信息为：
 * Detected change in 'D:\\code\\python\\local_python\\afinlflask\\aframecore\\log.py', reloading
 * Restarting with stat
石大胜华L v1.book+delete_book meta(auth='退订业务', module='退订')
石大胜华L v1.book+tuiding meta(auth='退订业务222', module='退订')
石大胜华L v1.book+tuidi343ng meta(auth='342345235', module='退订')
石大胜华L v1.book+xxxxx meta(auth='cedshiu', module='退订')
石大胜华L cms.auth+ceshiquanxian_01 meta(auth='订购11111', module='订购')
石大胜华L cms.auth+ceshiquanxian_02 meta(auth='订购22222', module='订购')
石大胜华L cms.auth+ceshiquanxian_03 meta(auth='订购3333', module='订购')
石大胜华L cms.auth+ceshiquanxian_04 meta(auth='订购4444', module='订购')
石大胜华L cms.auth+ceshiquanxian_05 meta(auth='订购55555', module='订购')
石大胜华L cms.auth+ceshiquanxian_fyabdab_01 meta(auth='孤单and收到货--002', module='滚蛋')
石大胜华L cms.auth+ceshiquanxian_fyabdab_02 meta(auth='孤单and收到货--001', module='滚蛋')
石大胜华L cms.log+get_logs meta(auth='查询所有日志', module='日志')
石大胜华L cms.log+get_user_logs meta(auth='搜索日志', module='日志')
石大胜华L cms.log+get_users meta(auth='查询日志记录的用户', module='日志')
石大胜华L cms.test+info meta(auth='查看lin的信息', module='信息')
 * Debugger is active!
 * Debugger PIN: 228-255-610
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [13/Jun/2019 12:45:15] "OPTIONS /cms/admin/authority HTTP/1.1" 200 -
2019-06-13 12:45:15.188 | INFO     | xmly_pro.app.app:request_cost_time:73 - =====================================================>>>>
2019-06-13 12:45:15.189 | INFO     | xmly_pro.app.app:request_cost_time:85 - 请求开始===>{"url": "http://localhost:5000/cms/admin/authority", "path": "/cms/admin/authority", "args": {}, "form": {}, "request_start_time": "2019-06-13T12:45:15.188432"}
2019-06-13 12:45:15.196 | INFO     | xmly_pro.app.app:log_response:120 - 请求结束===>{"url": "http://localhost:5000/cms/admin/authority", "path": "/cms/admin/authority", "args": {}, "form": {}, "request_start_time": "2019-06-13T12:45:15.188432", "req_time": "2019-06-13T12:45:15.196438", "resp_data": {"信息": {"查看lin的信息": ["cms.test+info"]}, "日志": {"搜索日志": ["cms.log+get_user_logs"], "查询所有日志": ["cms.log+get_logs"], "查询日志记录的用户": ["cms.log+get_users"]}, "滚蛋": {"孤单and收到货--001": ["cms.auth+ceshiquanxian_fyabdab_02"], "孤单and收到货--002": ["cms.auth+ceshiquanxian_fyabdab_01"]}, "订购": {"订购11111": ["cms.auth+ceshiquanxian_01"], "订购22222": ["cms.auth+ceshiquanxian_02"], "订购3333": ["cms.auth+ceshiquanxian_03"], "订购4444": ["cms.auth+ceshiquanxian_04"], "订购55555": ["cms.auth+ceshiquanxian_05"]}, "退订": {"342345235": ["v1.book+tuidi343ng"], "cedshiu": ["v1.book+xxxxx"], "退订业务": ["v1.book+delete_book"], "退订业务222": ["v1.book+tuiding"]}}, "cost_time": "0.00801"}
127.0.0.1 - - [13/Jun/2019 12:45:15] "GET /cms/admin/authority HTTP/1.1" 200 -
127.0.0.1 - - [13/Jun/2019 12:45:21] "OPTIONS /cms/admin/group HTTP/1.1" 200 -
2019-06-13 12:45:21.996 | INFO     | xmly_pro.app.app:request_cost_time:73 - =====================================================>>>>
2019-06-13 12:45:21.996 | INFO     | xmly_pro.app.app:request_cost_time:85 - 请求开始===>{"url": "http://localhost:5000/cms/admin/group", "path": "/cms/admin/group", "args": {}, "form": {}, "request_start_time": "2019-06-13T12:45:21.996219"}
127.0.0.1 - - [13/Jun/2019 12:45:22] "POST /cms/admin/group HTTP/1.1" 500 -
Traceback (most recent call last):
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\flask_cors\extension.py", line 110, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\flask_cors\extension.py", line 110, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\flask\app.py", line 1719, in handle_user_exception
    return handler(e)
  File "D:\code\python\local_python\afinlflask\aframecore\core.py", line 209, in handler
    raise e
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\code\python\local_python\afinlflask\aframecore\log.py", line 43, in wrap
    self.write_log()
  File "D:\code\python\local_python\afinlflask\aframecore\log.py", line 57, in write_log
    Log.create_log(message=self.message, user_id=self.user.id, user_name=self.user.nickname,
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 242, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 594, in get
    value = state._load_expired(state, passive)
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\sqlalchemy\orm\state.py", line 608, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "D:\code\python\local_python\lin-cms-flask-master03\venv\lib\site-packages\sqlalchemy\orm\loading.py", line 813, in load_scalar_attributes
    (state_str(state)))
sqlalchemy.orm.exc.DetachedInstanceError: Instance <User at 0x24bbff5a550> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)

**Comment by zyxyuanxiao** [comment]
发现是再调用：  print('user_id', self.user.id)的时候就直接报错了！

**Comment by fujiale33** [comment]
你好，前端版本号是多少？前端的last release 有个bug，就是数据格式改了。代码已经在master更新了。你参考一下是不是这个问题。[issues/175](https://github.com/TaleLin/lin-cms-vue/issues/175)

**Comment by fujiale33** [comment]
补充一下。    请把你完整的代码截图发一下。

**Comment by zyxyuanxiao** [comment]
> 补充一下。 请把你完整的代码截图发一下。

我发现问题点了：

我自己修改了core下的：
 @contextmanager
    def auto_commit(self):
        try:
            yield
            self.session.commit()
        except Exception as e:
            self.session.rollback()
            raise e
代码：

修改为了：

  def auto_commit_zyx(self):
        try:
            yield
            self.session.commit()
        except Exception as e:
            self.session.rollback()
            raise e
        # 如果加了这个自动的关闭的会回引起，日志的添加的时候出现的异常Instance is not bound to a Session
        finally:
            self.session.close()

导致了session会没操作一次关闭一次，所以引发了上面的异常！

**Comment by fujiale33** [comment]
哦 。  虽然可以这么做，但是不建议改源码，很不利于升级维护。 你是在用使用行为日志 的时候出现的这个问题是吗？  是如何使用出现的这个bug呢？能不能具体描述一下。
